### ISSUE TITLE
Run_Shabbos_Mode Trigger

### ISSUE THREAD

**Issue by fenderbender613** [clippycoder/Smartthings-Shabbos-Mode#1]
Thank you so much for your work on this SmartApp replacement for Shabbat-and-Holiday-Modes.  I am attempting to follow your AWS instructions as I too don't have a linux server available.  I am stuck on the instruction: "In Amazon EventBridge, create a trigger called 'Run_Shabbos_Mode' (it must be called exactly that), and schedule it with any valid cron() expression. Set it to run the lambda function 'Shabbos_Mode_Activator'."  I just was unsure about when it should be scheduled to run via cron.  Can you offer a more specific schedule like you did in your next instruction "run the function 'Get_Sunset_Time' before the earliest sunset of the year in your location every day."  Thank you again for posting your work on this as it will truly be helpful!

**Comment by clippycoder** [comment]
Hi. Thanks for pointing this out. I've responded to your specific request on the [smartthings forum](https://community.smartthings.com/t/smartapp-replacement-for-shabbat-and-holiday-modes/255274/16?u=rafael_m). I've also updated the readme so it should be more clear in the future.

**Comment by clippycoder** [comment]
@fenderbender613, If you've already uploaded the code to AWS, you should replace it with the newest version. There was a bug in the old program that would cause the code to fail if shabbos ever fell out on rosh chodesh. You don't need to completely reupload a zip; copying and pasting from the sources in the 'aws source code' folder directly into the lamda console works as well. If you have any other issues, be sure to tell me, and tell me when you get it working!

**Comment by fenderbender613** [comment]
Thank you so much for your responses.  I have scheduled it, and also applied your new updates on AWS.  I will know this Shabbos whether it is working properly and will be sure to let you know if I experience any issues.  Thanks again!
